### ISSUE TITLE
Add a schematic for AD9850 to esp32 wiring

### ISSUE THREAD

**Issue by swaldtmann** [Wei1234c/Signal_Generators#1]
Greetings! 
I am trying to rebuild your setup with a ESP32 board and a HC-SR08 (ad9850).

Having a hard time to find out the correct pins and the according micropython settings.

Actually I would like to have correct pins and code for this section:

> with_hardware_device = True
> 
> if with_hardware_device:
>     _spi = peripherals.SPI.get_uPy_spi(polarity = 1)
>     _ss = peripherals.Pin.get_uPy_pin(pin_id = 15, output = True) 
> else:
>     _spi = _ss = None  # using None for testing without actual hardware device.
> 
> bus = peripherals.SPI(_spi, _ss)
> ad = AD9833(bus) 
> 
> ad.reset()

for a ad9850 on a esp32

Any help is very much appreciated!

Best Regards!

**Comment by Wei1234c** [comment]
Sorry for late response. 

First of all, a bug in AD9850.py (line: 70) was fixed. Please git pull again.

for AD9850, please upload following files to ESP32:

```
ad98xx.py
ad9850.py
interfaces.py
peripherals.py
register.py
shift_register.py
```
Those files are in this repository and [here](https://github.com/Wei1234c/Utilities/tree/master/codes/utilities).

Four pins will be needed: 15, 14, 13, 4, as stated in following code example.

Then try following:

```

import gc

import ad9850
import peripherals
from shift_register import ShiftRegister


gc.collect()

_ss = peripherals.Pin.get_uPy_pin(15, output = True)
_clk = peripherals.Pin.get_uPy_pin(14, output = True)
_data = peripherals.Pin.get_uPy_pin(13, output = True)
_spi = ShiftRegister(stb_pin = _ss, clk_pin = _clk, data_pin = _data, lsbfirst = True, polarity = 1)
bus = peripherals.SPI(_spi, _ss)

_reset = peripherals.Pin.get_uPy_pin(4, output = True)
ad = ad9850.AD9850(bus = bus, pin_reset = _reset)
ad.reset()

ad.set_frequency(10.2e6)

gc.collect()

```

**Comment by swaldtmann** [comment]
Greetings!

Thank you for your response. Delay is not a problem at all. I appreciate your effort to help my with my hobby :-)

I struggled with line 70 in ad9850.py and found the same fix ;-)

Thank you for the pin assignment! Works great!

Best regards!
